In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

In [2]:
df=pd.read_csv("diabetes.csv")

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [6]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [7]:
df.isnull().sum()/df.shape[0]

Pregnancies                 0.0
Glucose                     0.0
BloodPressure               0.0
SkinThickness               0.0
Insulin                     0.0
BMI                         0.0
DiabetesPedigreeFunction    0.0
Age                         0.0
Outcome                     0.0
dtype: float64

In [8]:
df.duplicated().sum()

0

In [9]:
import seaborn as sns

In [10]:
sns.boxplot(df["texture_mean"])

KeyError: 'texture_mean'

In [ ]:
# for x in df.columns[::]:
#     if df[x].dtype==object:
#         continue
#     else:
#         q1=df[x].quantile(q=0.25)
#         q3=df[x].quantile(q=0.75)
#         IQR= q3-q1
        
#         low=q1-1.5*IQR
#         high=q3+1.5*IQR
#         df.loc[(df[x]<low)| (df[x]>high),x]=df[x].median()

In [ ]:
sns.boxplot(df["texture_mean"])

In [ ]:
#x= df['BMI']

In [ ]:
#df1=pd.get_dummies(x)

In [ ]:
#df=pd.concat([df,df1],axis=1)

In [ ]:
#df.drop(['BMI'],inplace=True,axis=1)

In [ ]:
#x= df['DiabetesPedigreeFunction']

In [ ]:
#df1=pd.get_dummies(x)

In [ ]:
#df=pd.concat([df,df1],axis=1)

In [ ]:
#df.drop(['DiabetesPedigreeFunction'],inplace=True,axis=1)

In [ ]:
df.info()

In [ ]:
#df.corr()

In [ ]:
df.shape

# multiple regression

In [11]:
x =df.drop('Outcome',axis=1).values
y = df["Outcome"]

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=40)

In [15]:
model = LinearRegression()

In [16]:
model.fit(x_train,y_train)

LinearRegression()

In [17]:
yp=model.predict(x_train)
ypd=model.predict(x_test)

In [18]:
from sklearn.metrics import r2_score

In [19]:
x = r2_score(y_train,yp)
X= r2_score(y_test,ypd)
print("R^2_test =",x)
print("R^2_train =",X)

R^2_test = 0.30236693153089045
R^2_train = 0.2904919300861245


# Logistic regresion 

In [61]:
x =df.drop('Outcome',axis=1)
y = df["Outcome"].values.reshape(-1,1)

In [62]:
# standardization
from sklearn.preprocessing import MinMaxScaler
# define Min max  Scaler 
mn = MinMaxScaler()
# transform data
scaled = mn.fit_transform(x)

In [63]:
# split the data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(scaled,y, test_size=0.2,random_state=40,stratify=y)

In [64]:
#import model 
from sklearn.linear_model import LogisticRegression

In [65]:
# instantiate 
model = LogisticRegression()

In [66]:
#  fit the model with data 
model.fit(x_train,y_train)

LogisticRegression()

In [67]:
# predict wiht test data 
y_pred = model.predict(x_test)
y_train_pred = model.predict(x_train)

In [68]:
model.score(x_train,y_train)

0.7785016286644951

In [70]:
model.score(x_test,y_test)

0.7467532467532467

### performance Measure of classification 

In [71]:
# import the matrics class  for test
from sklearn.metrics import confusion_matrix 
cnf_matrix = confusion_matrix(y_test, y_pred)
cnf_matrix

array([[91,  9],
       [30, 24]], dtype=int64)

In [72]:
# import the matrics class  for train 
from sklearn.metrics import confusion_matrix 
cnf = confusion_matrix(y_train, y_train_pred)
cnf

array([[366,  34],
       [102, 112]], dtype=int64)

In [73]:
### Report for Test
from sklearn.metrics import classification_report 

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.75      0.91      0.82       100
           1       0.73      0.44      0.55        54

    accuracy                           0.75       154
   macro avg       0.74      0.68      0.69       154
weighted avg       0.74      0.75      0.73       154



In [74]:
##### report for y_train 
from sklearn.metrics import classification_report 

print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.78      0.92      0.84       400
           1       0.77      0.52      0.62       214

    accuracy                           0.78       614
   macro avg       0.77      0.72      0.73       614
weighted avg       0.78      0.78      0.77       614



In [75]:
# predict performance measure for y_test
from sklearn import metrics 

print("Accuracy = ",metrics.accuracy_score(y_test,y_pred))
print("Precision = ",metrics.precision_score(y_test,y_pred))
print("Recall = ",metrics.recall_score(y_test,y_pred))

Accuracy =  0.7467532467532467
Precision =  0.7272727272727273
Recall =  0.4444444444444444


In [76]:
# predict performance measure for y_train 
from sklearn import metrics 

print("Accuracy = ",metrics.accuracy_score(y_train,y_train_pred))
print("Precision = ",metrics.precision_score(y_train,y_train_pred))
print("Accuracy = ",metrics.recall_score(y_train,y_train_pred))

Accuracy =  0.7785016286644951
Precision =  0.7671232876712328
Accuracy =  0.5233644859813084


In [77]:
# hyper tocnix


In [78]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import GridSearchCV
param_grid= {"C":[1,2,3,4,5,6,7,8,9,10], 
            "penalty":['l1',"l2"],
            "solver":['lbfgs','liblinear'],
            'max_iter':[10000,100000,1000000]} # parameters
grid_search = GridSearchCV(model,param_grid,scoring='precision',cv=5)# score
grid_search.fit(y_test,y_pred)

lr = grid_search.best_estimator_
grid_search.best_params_,grid_search.best_score_

({'C': 1, 'max_iter': 10000, 'penalty': 'l1', 'solver': 'liblinear'}, 0.0)

In [79]:
logreg=LogisticRegression(C= 1, max_iter= 1000000000, penalty='l1',solver= 'liblinear')
# fit the model with data
logreg.fit(x_train,y_train)
# prediction with test
y_pred=logreg.predict(x_test)
y_train_pred=logreg.predict(x_train)

In [80]:
# import the metrix class
from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(y_test,y_pred)
cnf_matrix

array([[86, 14],
       [23, 31]], dtype=int64)

In [37]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.76      0.91      0.83        95
           1       0.78      0.54      0.64        59

    accuracy                           0.77       154
   macro avg       0.77      0.72      0.73       154
weighted avg       0.77      0.77      0.76       154

